AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  KeyPair:
    Description: Choose your key pair
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bef6cc322bfff646
      InstanceType: t2.micro
      KeyName: 
        !Ref KeyPair
      SecurityGroupIds: 
        - !GetAtt SecGroup.GroupId
      Tags: 
        - Key: Name
          Value: !Sub "Web Server of ${AWS::StackName}"
      UserData:
        !Base64 |
          #!/bin/bash
          yum update -y
          yum install git -y
          yum install python3 python3-pip -y
          pip3 install flask
          git clone https://github.com/rektozarius/hands_on.git
          cd ./hands_on/AWS/Project-001-Roman-Numerals-Converter/
          python3 app.py
  SecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and HTTP
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
Outputs:
  Output:
    Description: Displays roman-numeral-converter website url
    Value: !Join [ '', [ 'http://',!GetAtt WebServer.PublicDnsName]]